### ISSUE TITLE
Template? 

### ISSUE THREAD

**Issue by hdrdavies** [foundersandcoders/newsletter#1]
Do we need a template for the email?

**Comment by rub1e** [comment]
yes - it should be as templated as possible so all we have to do is drop content into the relevant places and send it

Whatever mailing service we use (mandrill etc) will have plenty

**Comment by hdrdavies** [comment]
I have no experience with these mass mailing services - which one shall we plump for?

**Comment by NataliaLKB** [comment]
@hdrdavies and @rub1e we have a mailchimp account. @minaorangina and @sofer both have logins.

**Comment by hdrdavies** [comment]
Thank you @NataliaLKB

**Comment by iteles** [comment]
Linked to #2
