### ISSUE TITLE
Master list of historical newsletters?

### ISSUE THREAD

**Issue by iteles** [foundersandcoders/newsletter#14]
For Ladies Who Code London, I keep a master list of past newsletters in the readme and find that it's quite a nice thing to be able to look back on: https://github.com/ladieswhocode/london#past-newsletters 

Is it worth doing this for the F&C newsletter? :blush:

**Comment by rub1e** [comment]
http://kb.mailchimp.com/campaigns/archives/set-up-your-campaign-archive

**Comment by rub1e** [comment]
We can have it as a section on the website (perhaps in place of our "blog")

**Comment by hdrdavies** [comment]
Absoutely @iteles ! That's the idea with the current folder structure

**Comment by iteles** [comment]
Wonderful :+1:
