### ISSUE TITLE
More press features for November

### ISSUE THREAD

**Issue by hdrdavies** [foundersandcoders/newsletter#20]
Harry Fox's company video to be added
-rejig of the titling

**Comment by iteles** [comment]
Curious! Which video is this?

**Comment by hdrdavies** [comment]
https://www.youtube.com/watch?v=qxnu1oAfGb4&feature=youtu.be

**Comment by iteles** [comment]
Didn't even know this existed! Filmed during the summer :+1:

**Comment by NataliaLKB** [comment]
*Joe Tanner

Not Harry Fox

Great Video :+1:
