### ISSUE TITLE
Add a blog entry 

### ISSUE THREAD

**Issue by hdrdavies** [foundersandcoders/newsletter#27]
@abdiahmed please detail your thoughts earlier which sounded really interesting.

**Comment by abdiahmed** [comment]
There isn't a blog section on the website, and I think it would complement what we do at FAC to periodically release tutorial blogs to the wider community. This can add more meat to the newsletter that gets sent out to the email subscribers. This would also give FAC and it's members more exposure online.

**Comment by iteles** [comment]
Note: There used to be a blog but it was removed because getting content for it was like pulling teeth. 

Definitely a great idea, would love to see this happen!

**Comment by hdrdavies** [comment]
@iteles I thought I recalled that. Would it be wise to elect someone as a blog 'chief editor' in the same way there is one for the newsletter? It would be great to see it on the website again.

**Comment by iteles** [comment]
@hdrdavies Absolutely! We had that last time too, the problem really was that there was nothing to 'edit' :wink:

**Comment by abdiahmed** [comment]
I'd be more than happy to become a co-editor with someone, we could try and making it work once again. I think if we go for a simple publishing schedule, like once every two weeks or even once a month, and see how it goes.

**Comment by hdrdavies** [comment]
I believe this was raised as a task-group in the recent FAC structuring
