### ISSUE TITLE
Content for January Issue 

### ISSUE THREAD

**Issue by hdrdavies** [foundersandcoders/newsletter#28]
@sofer @iteles @rub1e Interested to hear your ideas on the content for the January Newsletter. I've added the template here:

https://github.com/foundersandcoders/newsletter/blob/master/2016-Jan/template.md

Could I get your thoughts on the following:
* What would we like to announce about the Ramallah project?
* What we would like to say about the Morpeth School sessions
* What FAC-related activities Josh has been conducting in India (it would make great content)
* Whether there are any big events we're attending / running in the near future that I've forgotten about 

...and of course if you have any ideas of other content!

**Comment by sofer** [comment]
Applications are now open for Summer 2016.

**Comment by iteles** [comment]
Node girls will be on 27th Feb and we should have a link for applications soon. What's the deadline for getting something to you?

**Comment by hdrdavies** [comment]
@iteles I would say the newsletter should be sent by Friday latest.

**Comment by sofer** [comment]
Exploring the World of APIs http://www.meetup.com/founderscoders/events/228353797/ ion Feb 20th.

Ask @sohilpandya and @RachBLondon for details.

**Comment by sofer** [comment]
@hdrdavies *This term, we have started running a coding club for 6th formers at nearby Morpeth School. We have really enjoyed working with young people who have almost no experience of building websites or writing code and we hope eventually some of them will be inspired to join our programme.*

**Comment by rub1e** [comment]
@hdrdavies sorry, totally missed this issue. I added an announcement about the upcoming alumni survey to the template - I'm now taking it out as I think it can be sent just to alumni when we send a reminder about the monthly biz meeting next week. 

Would you like me to get in touch with Josh? Given that it's going out tomorrow, could we save josh for next time and link to Per's youtube coding session instead (just in the interests of expediency!)

**Comment by rub1e** [comment]
Also, perhaps we can also save the cohort project of the month for next time too - unless something really jumps out from their first couple of weeks?

**Comment by hdrdavies** [comment]
@rub1e Yes let's leave Josh for next time, and which of Per's videos are we talking about here? Would you mind linking me?

**Comment by rub1e** [comment]
https://www.youtube.com/watch?v=_tyRjMNVRuc

https://medium.com/learning-new-stuff/sunday-coding-session-javascript-and-react-js-11bcd40f237b#.45zh0sad4

**Comment by hdrdavies** [comment]
Thanks @rub1e !!!
