### ISSUE TITLE
length

### ISSUE THREAD

**Issue by rub1e** [foundersandcoders/newsletter#3]
I'm not convinced that "no scroll" is the way to go, or even possible. Regardless of length, there will be plenty of people who just won't open/read it - I think we should go with whatever content we think is worthwhile and re-evaluate after we've got a few under our belt - not let the tail wag the dog

**Comment by hdrdavies** [comment]
Are there any newsletters you subscribe to that have a good length? I would agree that 'no scroll' is very ambitious.

**Comment by nelsonic** [comment]
no scroll on a mobile device should be the goal... :laughing:

**Comment by rub1e** [comment]
I reckon we could get away with just implying most of the content

**Comment by nelsonic** [comment]
lol. or just a collation of the 3 most popular tweets, 2 instagrams & 1 vine of the week...? :wink:

**Comment by msmichellegar** [comment]
I don't believe scrolling is the bottleneck to get people reading a newsletter. Prioritising correctly, and having good content "above the fold" (aka in view) is definitely important. But I don't think "no scroll" is the way to go. How much content could we really fit on a mobile device with no scroll? Maybe a heading, photo and three sentences max.

I'm imagining most of our subscribers are invested in the ongoing story of FAC. We have to give people something of value. If subscribers find the content too brief or uninteresting, they'll *definitely* not open it the next month.

**Comment by rub1e** [comment]
totes agree - most of our subscribers are former FACcers - and if they can't be bothered to open one email a month from us then they can do one as far as I'm concerned

Although I do think @nelsonic might have been joking about no scroll on a mobile...

**Comment by nelsonic** [comment]
The newsletter should just be a [*Yo*](https://en.wikipedia.org/wiki/Yo_(app))

**Comment by hdrdavies** [comment]
Agreed that "no scroll" was a silly principle, let's just try to be concise and killer with content

**Comment by msmichellegar** [comment]
Perf :)

**Comment by nelsonic** [comment]
@hdrdavies I don't know who started the "no scroll" chat but I'm glad there's a pragmatic conclusion. Content #FTW :+1:
