### ISSUE TITLE
Content for February Issue

### ISSUE THREAD

**Issue by hdrdavies** [foundersandcoders/newsletter#30]
@rub1e Mentioned reaching out to Josh and @sofer suggested this issue may be a good time to announce the Ramallah project.

I also imagine by this time we may have some FAC videos from @andrewMacmurray 

* Jack and Eoin's react tutorial
* Tormod / Gethin hackathon win
* Link to our instagram

Everyone is welcome to contribute ideas, big or small.

**Comment by sofer** [comment]
Ask @tormod17 and @thegsi about their iot hackathon victory.

**Comment by rub1e** [comment]
I sent Josh a message - will share his reply when I have it

**Comment by hdrdavies** [comment]
Just added it @sofer actually haha

**Comment by rub1e** [comment]
When do you want to send it out? We should set a submission deadline and announce it to FAC gitter to nudge them.

**Comment by hdrdavies** [comment]
Normally last week of the month

**Comment by hdrdavies** [comment]
@sofer is this a good time to announce Ramallah?

**Comment by sofer** [comment]
@hdrdavies not yet, but my guess is that we will have more news (and a video!) for March.

**Comment by hdrdavies** [comment]
@sofer @rub1e @katpas What could we say about the TechHub talk?

**Comment by hdrdavies** [comment]
and is there anything similar coming up?

**Comment by iteles** [comment]
@hdrdavies [This tweet](https://twitter.com/TechHub/status/699578833264058368) on the techhub talk is worth embedding if possible. Don't think there are any new talks in the diary yet, but @thegsi and @JackTierney are working on it :+1:

**Comment by iteles** [comment]
In dwyl news, we've had lots of people join since the last one - worth adding?
Also https://github.com/dwyl/learn-redux

**Comment by hdrdavies** [comment]
We've recently decided for the newsletter to be once every 2 months - the content here will be carried over to the next issue :smile:
