### ISSUE TITLE
'Leadership team'

### ISSUE THREAD

**Issue by hdrdavies** [foundersandcoders/newsletter#5]
Rotating team of chief editor and co-editor which changes every 4-6 months could damage continuity. Possibility of a long-term commissioning editor with an editorial committee could work, with the commissioning editor specifying when they would like to step down.

**Comment by rub1e** [comment]
I know I'm lurching around a bit on this issue...

I think we need to be realistic about how long people tend to stay in the space when they've finished the course and how much time they have when they do - not sure how possible it would be to rely on 6 months

So I totally see the sense in having a senior/junior system where the senior editor is a recent FACx grad, supported by either an editorial committee or an "assistant" from FACx+1 who then ascends to the top role.

And I think my worries about continuity would be addressed if we just make sure to document all of our processes diligently...

**Comment by hdrdavies** [comment]
@rub1e Yes I feel good documentation to ensure continuity is all we need. Hopefully the repo will satisfy that. In dire circumstances the editorial team can step down if there are suitable replacements for them.
