### ISSUE TITLE
Are we using MailChimp?

### ISSUE THREAD

**Issue by msmichellegar** [foundersandcoders/newsletter#6]
It's by far the best in my experience. I think most of us agree.

**Comment by NataliaLKB** [comment]
:+1: :monkey_face:

**Comment by iteles** [comment]
Links to https://github.com/foundersandcoders/newsletter/issues/1#issuecomment-155116916.

**Comment by hdrdavies** [comment]
We will be using this @msmichellegar

**Comment by msmichellegar** [comment]
Cool!
