### ISSUE TITLE
No co-editor at present 

### ISSUE THREAD

**Issue by hdrdavies** [foundersandcoders/newsletter#7]
At current there is only a chief editor.

**Comment by rub1e** [comment]
I think you'll have to live without on this one - but it's only the first issue - and there won't be another one before FAC7 - so you'll have some support starting with Issue No.2

**Comment by hdrdavies** [comment]
Well... after the November issue there'll be the December one as well as the January one - which will likely come without a FAC7er's help as it will be released around 18th Jan which is when they arrive.

**Comment by hdrdavies** [comment]
The need for a December issue (given that things may be quiet in that particular month) is under review [here](https://github.com/foundersandcoders/newsletter/issues/13)
